CREATE OR REPLACE PROCEDURE NUMEROS_FIBONACCI (p_INTERACOES IN FLOAT, p_NUMEROFIBO OUT FLOAT)
IS
   v_FIBO1 FLOAT := 0;
   v_FIBO2 FLOAT := 1;
   v_FIBO_ATUAL FLOAT := 0;
   v_CONTADOR FLOAT := 1;
   v_INTERACOES FLOAT := 1;
BEGIN
   IF p_INTERACOES > 1 THEN
      LOOP
         v_FIBO_ATUAL := v_FIBO1 + v_FIBO2;
         v_FIBO1 := v_FIBO2;
         v_FIBO2 := v_FIBO_ATUAL;
         v_CONTADOR := v_CONTADOR + 1;
      EXIT WHEN v_CONTADOR >= p_INTERACOES;
      END LOOP;
   END IF;
   p_NUMEROFIBO := v_FIBO_ATUAL;
END;


SET SERVEROUTPUT ON;

declare
    v_NUMEROFIBO float;
    v_INTERACOES INTEGER := 5;
begin

    NUMEROS_FIBONACCI_FOR (v_INTERACOES, v_NUMEROFIBO);
    dbms_output.put_line('v_NUMEROFIBO = ' || v_NUMEROFIBO);
end;


--- OTIMIZADO, USANDO FOR

CREATE OR REPLACE PROCEDURE NUMEROS_FIBONACCI_FOR (p_INTERACOES IN FLOAT, p_NUMEROFIBO OUT FLOAT)
IS
   v_FIBO1 FLOAT := 0;
   v_FIBO2 FLOAT := 1;
   v_FIBO_ATUAL FLOAT := 0;
BEGIN
   IF p_INTERACOES > 1 THEN
      FOR v_CONTADOR IN 2..p_INTERACOES LOOP
         v_FIBO_ATUAL := v_FIBO1 + v_FIBO2;
         v_FIBO1 := v_FIBO2;
         v_FIBO2 := v_FIBO_ATUAL;
      END LOOP;
   END IF;
   p_NUMEROFIBO := v_FIBO_ATUAL;
END;

--- COM WHILE

CREATE OR REPLACE PROCEDURE NUMEROS_FIBONACCI_WHILE (p_INTERACOES IN FLOAT, p_NUMEROFIBO OUT FLOAT)
IS
   v_FIBO1 FLOAT := 0;
   v_FIBO2 FLOAT := 1;
   v_FIBO_ATUAL FLOAT := 0;
   v_CONTADOR FLOAT := 1;
   v_INTERACOES FLOAT := 1;
BEGIN
   IF p_INTERACOES > 1 THEN
      WHILE v_CONTADOR < p_INTERACOES LOOP
         v_FIBO_ATUAL := v_FIBO1 + v_FIBO2;
         v_FIBO1 := v_FIBO2;
         v_FIBO2 := v_FIBO_ATUAL;
         v_CONTADOR := v_CONTADOR + 1;
      END LOOP;
   END IF;
   p_NUMEROFIBO := v_FIBO_ATUAL;
END;