SELECT *  
FROM tabela_de_produtos;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
END
)
FROM TABELA_DE_PRODUTOS;



SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE 
    WHEN PRECO_DE_LISTA >= 12 THEN 'Produto caro'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'Produto em conta'
    ELSE 'Produto barato'
END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE 
    WHEN PRECO_DE_LISTA >= 12 THEN 'Produto caro'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'Produto em conta'
    ELSE 'Produto barato'
END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga';


-- Prolixo
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE 
    WHEN PRECO_DE_LISTA >= 12 THEN 'Produto caro'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'Produto em conta'
    ELSE 'Produto barato'
END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS
ORDER BY (CASE 
    WHEN PRECO_DE_LISTA >= 12 THEN 'Produto caro'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'Produto em conta'
    ELSE 'Produto barato'
END);


-- Melhor
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE 
    WHEN PRECO_DE_LISTA >= 12 THEN 'Produto caro'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'Produto em conta'
    ELSE 'Produto barato'
END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS
ORDER BY CLASSIFICACAO;


SELECT NOME,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Clientes grandes'
    WHEN LIMITE_DE_CREDITO < 150000 AND LIMITE_DE_CREDITO >= 110000 THEN 'Clientes medios'
    ELSE 'Clientes pequenos'
END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES
ORDER BY CLASSIFICACAO DESC;
