---PROLIXO
SELECT TABELA_DE_PRODUTOS.* 
FROM TABELA_DE_PRODUTOS
WHERE 1=1
AND ROWNUM <=1000000
ORDER BY ROWNUM;

-- NORMAL
SELECT * 
FROM TABELA_DE_PRODUTOS;

--HAVING
SELECT* FROM tabela_de_clientes;


SELECT ESTADO, SUM(LIMITE_DE_CREDITO) FROM tabela_de_clientes GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) 
FROM tabela_de_clientes 
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) > 850000;


SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS "MAIOR PREÇO" , MIN(PRECO_DE_LISTA) AS "MENOR PREÇO"
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;


SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS "MAIOR PREÇO" , MIN(PRECO_DE_LISTA) AS "MENOR PREÇO"
FROM TABELA_DE_PRODUTOS 
WHERE PRECO_DE_LISTA >= 10
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS "MAIOR PREÇO" , MIN(PRECO_DE_LISTA) AS "MENOR PREÇO"
FROM TABELA_DE_PRODUTOS 
WHERE PRECO_DE_LISTA >= 10
GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) >= 20;



SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO ORDER BY SUM(QUANTIDADE) DESC;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;


//=======================================



