SELECT 
TC.CPF AS "CPF DO CADASTRO",
TC.NOME AS "NOME DO CLIENTE",
NF.CPF AS "CPF NA0 NOTA FISCAL"
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
NOTAS_FISCAIS NF
ON
TC.CPF = NF.CPF;

SELECT DISTINCT
TC.CPF AS "CPF DO CADASTRO",
TC.NOME AS "NOME DO CLIENTE",
NF.CPF AS "CPF NA0 NOTA FISCAL"
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
NOTAS_FISCAIS NF
ON
TC.CPF = NF.CPF;

SELECT COUNT(*) AS QUANTIDADE FROM TABELA_DE_CLIENTES;

DESC TABELA_DE_CLIENTES;


INSERT INTO TABELA_DE_CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, 
SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA) 
VALUES ('23412632331', 'Juliana Silva', 'R. Tramandai', '', 'Bangu', 'Rio de Janeiro', 
'RJ', '23400000', TO_DATE('1989-02-04','YYYY-MM-DD'), 28, 'F', 180000.0000, 24500, 0);


SELECT DISTINCT
TC.NOME,
NF.CPF
FROM
TABELA_DE_CLIENTES TC
LEFT JOIN
NOTAS_FISCAIS NF
ON
TC.CPF = NF.CPF;


--Quero os clientes que não compraram nada i.e. que não tem nota fiscal associada
SELECT DISTINCT
TC.NOME,
NF.CPF
FROM
TABELA_DE_CLIENTES TC
LEFT JOIN
NOTAS_FISCAIS NF
ON
TC.CPF = NF.CPF
WHERE NF.CPF IS NULL;

SELECT DISTINCT
TC.CPF,
TC.NOME
FROM
TABELA_DE_CLIENTES TC
LEFT JOIN
NOTAS_FISCAIS NF
ON
TC.CPF = NF.CPF
WHERE NF.CPF IS NULL;