INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (1, 'Varejo'); 


-- Run on system user
ALTER USER cursoplsql QUOTA UNLIMITED ON USERS;


SELECT * FROM SEGMERCADO;


DELETE FROM SEGMERCADO;

DESC SEGMERCADO;

-- Insert via PL/SQL
DECLARE
    v_ID NUMBER(5) := 1;
    v_DESCRICAO VARCHAR2(100) := 'Varejo';
BEGIN

    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, V_DESCRICAO); 
    v_ID := 2;
    V_DESCRICAO := 'Industry';
    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, V_DESCRICAO); 
    COMMIT;
END;



DECLARE
   v_COD VARCHAR(5):= '41235';
   v_DESCRICAO VARCHAR2(100) := 'Sabor de Outono - Uva - 500 ml';
   v_CATEGORIA VARCHAR(100):= 'Sucos de Frutas';
BEGIN
   INSERT INTO PRODUTO_EXERCICIO (COD, DESCRICAO, CATEGORIA) VALUES (v_COD, v_DESCRICAO, v_CATEGORIA);
   COMMIT;
END;


SELECT * FROM PRODUTO_EXERCICIO;

DESC PRODUTO_EXERCICIO;


---percent type: Use same type of table in a BIND MODE.
DECLARE
    v_ID SEGMERCADO.ID%TYPE := 2;
    v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE := 'Têxtil';
BEGIN

    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, V_DESCRICAO); 
    v_ID := 2;
    COMMIT;
END;


SELECT * FROM SEGMERCADO;