DECLARE
   v_ID SEGMERCADO.ID%type :=5;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Serviços';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO); 
   COMMIT;
END;

SELECT * FROM SEGMERCADO;
SELECT * FROM SEGMERCADO WHERE DESCRICAO = 'Atacado';
SELECT * FROM SEGMERCADO WHERE DESCRICAO = 'atacado';

SELECT * FROM SEGMERCADO WHERE UPPER(DESCRICAO) = 'ATACADO'; 

SELECT * FROM SEGMERCADO WHERE UPPER(DESCRICAO) = UPPER('serviços'); 


DECLARE
   v_ID SEGMERCADO.ID%type :=5;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Serviços';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, UPPER(v_DESCRICAO)); 
   COMMIT;
END;


delete from segmercado where ID >= 4
