DECLARE
   v_ID SEGMERCADO.ID%type :=5;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Atacado';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO); 
   COMMIT;
END;


SELECT * FROM SEGMERCADO;



DECLARE
   v_ID SEGMERCADO.ID%type := 3;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Atacadista';
BEGIN
   UPDATE SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID; 
   
   v_ID := 1;
   v_DESCRICAO := 'Varejista';
   UPDATE SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID; 
   
   v_ID := 2;
   v_DESCRICAO := 'Industrial';
   UPDATE SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID; 
   COMMIT;

END;


--- REPLACE

SELECT * FROM produto_exercicio;

DECLARE
  v_COD produto_exercicio.cod%type;
BEGIN
   v_COD := '41232';
   UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO,'-','>') WHERE COD = v_COD;
   v_COD := '32223';
   UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO,'-','>') WHERE COD = v_COD;
   
   v_COD := '41231';
   UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO,'-','>') WHERE COD = v_COD;
   
   v_COD := '41235';
   UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO,'-','>') WHERE COD = v_COD;
   
   COMMIT;
END;

-- DELETE various

DECLARE
   v_ID SEGMERCADO.ID%type :=5;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Esportistas';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO); 
   COMMIT;
END;


SELECT * FROM SEGMERCADO;

UPDATE SEGMERCADO SET DESCRICAO = UPPER(DESCRICAO) WHERE ID = 5;



DECLARE
   v_ID SEGMERCADO.ID%type :=5;
BEGIN
   DELETE FROM SEGMERCADO WHERE ID = v_ID;
   COMMIT;
END;


-- Alterar categoria

DECLARE
   v_COD produto_exercicio.cod%type := '92347';
   v_DESCRICAO produto_exercicio.descricao%type := 'Aroma do Campo - Mate - 1 Litro';
   v_CATEGORIA produto_exercicio.categoria%type := 'Águas';
BEGIN
   INSERT INTO PRODUTO_EXERCICIO (COD, DESCRICAO, CATEGORIA) VALUES (v_COD, REPLACE(v_DESCRICAO,'-','>')
   , v_CATEGORIA);
   COMMIT;
END;
DECLARE
   v_ID SEGMERCADO.ID%type :=5;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Atacado';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO); 
   COMMIT;
END;


SELECT * FROM SEGMERCADO;



DECLARE
   v_ID SEGMERCADO.ID%type := 3;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Atacadista';
BEGIN
   UPDATE SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID; 
   
   v_ID := 1;
   v_DESCRICAO := 'Varejista';
   UPDATE SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID; 
   
   v_ID := 2;
   v_DESCRICAO := 'Industrial';
   UPDATE SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID; 
   COMMIT;

END;


--- REPLACE

SELECT * FROM produto_exercicio;

DECLARE
  v_COD produto_exercicio.cod%type;
BEGIN
   v_COD := '41232';
   UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO,'-','>') WHERE COD = v_COD;
   v_COD := '32223';
   UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO,'-','>') WHERE COD = v_COD;
   
   v_COD := '41231';
   UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO,'-','>') WHERE COD = v_COD;
   
   v_COD := '41235';
   UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO,'-','>') WHERE COD = v_COD;
   
   COMMIT;
END;

-- DELETE various

DECLARE
   v_ID SEGMERCADO.ID%type :=5;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Esportistas';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO); 
   COMMIT;
END;


SELECT * FROM SEGMERCADO;

UPDATE SEGMERCADO SET DESCRICAO = UPPER(DESCRICAO) WHERE ID = 5;



DECLARE
   v_ID SEGMERCADO.ID%type :=5;
BEGIN
   DELETE FROM SEGMERCADO WHERE ID = v_ID;
   COMMIT;
END;





DECLARE
   v_COD produto_exercicio.cod%type := '92347';
   v_CATEGORIA produto_exercicio.categoria%type := 'Mate';
BEGIN
   UPDATE PRODUTO_EXERCICIO SET CATEGORIA = v_CATEGORIA WHERE COD = v_COD;
   COMMIT;
END;


SELECT * FROM PRODUTO_EXERCICIO;

